### ISSUE TITLE
main.py does not take command line args 'train' and 'test'

### ISSUE THREAD

**Issue by tomhoag** [despoisj/DeepEyeControl#2]
main.py does not take command line args 'train' and 'test'

model.py does take those args but seems to be out of order in sequence of actions to be taken?

**Comment by despoisj** [comment]
Good catch, I will correct the read me!
However, I don't see what you mean about order ?

**Comment by tomhoag** [comment]
I was just thinking through the order in which model, main (others?) need to be run.  I believe that what needs to be done is

python model.py train (to train the model)

python main.py (to use the model to classify eye movements -- and ultimately act upon them)

correct?

**Comment by despoisj** [comment]
Absolutely correct !
